const checklistNodes = {
  checklist_subjects_nodes: [
    {
      id: 7091,
      element_id: 1768,
      subject_id: 3,
      tool_type: 1,
      tool_type_id: 624,
      qid: 624,
      value_id: 47022,
      checklist_subject_id: 0,
      answer: "",
      checklist_node_id: 12879,
      given_by: 0,
      given_dt: "0000-00-00",
      approved_by: 0,
      approved_dt: "0000-00-00",
      yes_no: 5,
      ans: 0,
      short_checklist: "Is there a documented inventory count policy?",
      full_checklist: "Has the company established and communicated a policy outlining the procedures for inventory counting?",
      source: 1,
      desired_result: 1,
      na_as: 0,
      answer_type: 0,
      answer_type_selection_id: 0,
      reject_approve_notes: "",
      created_node_type: 0,
      memo_cnt: 0,
      notes_cnt: 0,
      comm_cnt: 0,
      wpr_cnt: 0,
      attachment_cnt: 0,
      guidance_cnt: 0,
      extcommu_cnt: 0,
      up_to_date: 0,
      is_assignment_attachment_required: 0,
      created_on: "2025-03-24 06:35:02",
      node_status: 1,
      exception_found: 1,
      question_attachment: 0
    },
    {
      id: 7091,
      element_id: 1768,
      subject_id: 3,
      tool_type: 1,
      tool_type_id: 624,
      qid: 624,
      value_id: 47023,
      checklist_subject_id: 0,
      answer: "",
      checklist_node_id: 12880,
      given_by: 0,
      given_dt: "0000-00-00",
      approved_by: 0,
      approved_dt: "0000-00-00",
      yes_no: 5,
      ans: 0,
      short_checklist: "Are counts conducted by independent personnel?",
      full_checklist: "Are inventory counts performed by individuals who are independent of the inventory management process?",
      source: 1,
      desired_result: 1,
      na_as: 0,
      answer_type: 0,
      answer_type_selection_id: 0,
      reject_approve_notes: "",
      created_node_type: 0,
      memo_cnt: 0,
      notes_cnt: 0,
      comm_cnt: 0,
      wpr_cnt: 0,
      attachment_cnt: 0,
      guidance_cnt: 0,
      extcommu_cnt: 0,
      up_to_date: 0,
      is_assignment_attachment_required: 0,
      created_on: "2025-03-24 06:35:02",
      node_status: 1,
      exception_found: 0,
      question_attachment: 0
    },
    {
      id: 7091,
      element_id: 1768,
      subject_id: 3,
      tool_type: 1,
      tool_type_id: 624,
      qid: 624,
      value_id: 47024,
      checklist_subject_id: 0,
      answer: "",
      checklist_node_id: 12881,
      given_by: 0,
      given_dt: "0000-00-00",
      approved_by: 0,
      approved_dt: "0000-00-00",
      yes_no: 5,
      ans: 0,
      short_checklist: "Is there a pre-count authorization process?",
      full_checklist: "Is there a formal process for obtaining authorization before conducting the physical inventory count?",
      source: 1,
      desired_result: 1,
      na_as: 0,
      answer_type: 0,
      answer_type_selection_id: 0,
      reject_approve_notes: "",
      created_node_type: 0,
      memo_cnt: 0,
      notes_cnt: 0,
      comm_cnt: 0,
      wpr_cnt: 0,
      attachment_cnt: 0,
      guidance_cnt: 0,
      extcommu_cnt: 0,
      up_to_date: 0,
      is_assignment_attachment_required: 0,
      created_on: "2025-03-24 06:35:02",
      node_status: 1,
      exception_found: 0,
      question_attachment: 0
    },
    {
      id: 7091,
      element_id: 1768,
      subject_id: 3,
      tool_type: 1,
      tool_type_id: 624,
      qid: 624,
      value_id: 47025,
      checklist_subject_id: 0,
      answer: "",
      checklist_node_id: 12882,
      given_by: 0,
      given_dt: "0000-00-00",
      approved_by: 0,
      approved_dt: "0000-00-00",
      yes_no: 5,
      ans: 0,
      short_checklist: "Are count instructions clear and standardized?",
      full_checklist: "Are instructions for counting inventory clear, standardized, and provided to all personnel involved in the count?",
      source: 1,
      desired_result: 1,
      na_as: 0,
      answer_type: 0,
      answer_type_selection_id: 0,
      reject_approve_notes: "",
      created_node_type: 0,
      memo_cnt: 0,
      notes_cnt: 0,
      comm_cnt: 0,
      wpr_cnt: 0,
      attachment_cnt: 0,
      guidance_cnt: 0,
      extcommu_cnt: 0,
      up_to_date: 0,
      is_assignment_attachment_required: 0,
      created_on: "2025-03-24 06:35:02",
      node_status: 1,
      exception_found: 0,
      question_attachment: 0
    }
  ]
};

module.exports = { checklistNodes };
