const sharecaptial = [
  {
    "sl_no": 1,
    "shareholder_name": "John Doe",
    "no_of_shares": 1116,
    "date_of_issue": "2023-09-06",
    "instrument_no_from": 4410,
    "instrument_no_to": 7304,
    "mode_of_issue": "Allotment",
    "is_promoter": "No",
    "consideration": "Conversion",
    "issue_value_per_share": 52,
    "total_issue_value": 58032,
    "face_value_per_share": 50,
    "face_value": 55800,
    "type_of_capital": "Equity",
    "class_of_capital": "Class 2"
  },
  {
    "sl_no": 2,
    "shareholder_name": "Jane Smith",
    "no_of_shares": 3655,
    "date_of_issue": "2020-11-05",
    "instrument_no_from": 2030,
    "instrument_no_to": 7077,
    "mode_of_issue": "Split",
    "is_promoter": "Yes",
    "consideration": "Conversion",
    "issue_value_per_share": 23,
    "total_issue_value": 84065,
    "face_value_per_share": 10,
    "face_value": 36550,
    "type_of_capital": "Equity",
    "class_of_capital": "Class 1"
  },
  {
    "sl_no": 3,
    "shareholder_name": "Alice Johnson",
    "no_of_shares": 2034,
    "date_of_issue": "2023-04-24",
    "instrument_no_from": 1523,
    "instrument_no_to": 8089,
    "mode_of_issue": "Bonus",
    "is_promoter": "No",
    "consideration": "Cash",
    "issue_value_per_share": 103,
    "total_issue_value": 209502,
    "face_value_per_share": 100,
    "face_value": 203400,
    "type_of_capital": "Equity",
    "class_of_capital": "Class 2"
  },
  {
    "sl_no": 4,
    "shareholder_name": "Robert Brown",
    "no_of_shares": 1312,
    "date_of_issue": "2021-09-06",
    "instrument_no_from": 3606,
    "instrument_no_to": 5776,
    "mode_of_issue": "Bonus",
    "is_promoter": "Yes",
    "consideration": "Contract",
    "issue_value_per_share": 12,
    "total_issue_value": 15744,
    "face_value_per_share": 10,
    "face_value": 13120,
    "type_of_capital": "Preference",
    "class_of_capital": "Class 2"
  },
  {
    "sl_no": 5,
    "shareholder_name": "Emily Davis",
    "no_of_shares": 1458,
    "date_of_issue": "2023-03-02",
    "instrument_no_from": 4332,
    "instrument_no_to": 9014,
    "mode_of_issue": "Split",
    "is_promoter": "Yes",
    "consideration": "Contract",
    "issue_value_per_share": 107,
    "total_issue_value": 156006,
    "face_value_per_share": 100,
    "face_value": 145800,
    "type_of_capital": "Equity",
    "class_of_capital": "Class 1"
  },
  {
    "sl_no": 6,
    "shareholder_name": "Michael Wilson",
    "no_of_shares": 4249,
    "date_of_issue": "2022-12-02",
    "instrument_no_from": 4665,
    "instrument_no_to": 6884,
    "mode_of_issue": "Allotment",
    "is_promoter": "No",
    "consideration": "Conversion",
    "issue_value_per_share": 109,
    "total_issue_value": 463141,
    "face_value_per_share": 100,
    "face_value": 424900,
    "type_of_capital": "Equity",
    "class_of_capital": "Class 1"
  },
  {
    "sl_no": 7,
    "shareholder_name": "David Clark",
    "no_of_shares": 2584,
    "date_of_issue": "2022-02-01",
    "instrument_no_from": 2448,
    "instrument_no_to": 6518,
    "mode_of_issue": "Split",
    "is_promoter": "No",
    "consideration": "Cash",
    "issue_value_per_share": 19,
    "total_issue_value": 49096,
    "face_value_per_share": 10,
    "face_value": 25840,
    "type_of_capital": "Equity",
    "class_of_capital": "Class 2"
  },
  {
    "sl_no": 8,
    "shareholder_name": "Sophia White",
    "no_of_shares": 3160,
    "date_of_issue": "2023-11-09",
    "instrument_no_from": 2235,
    "instrument_no_to": 7032,
    "mode_of_issue": "Bonus",
    "is_promoter": "No",
    "consideration": "ESOP",
    "issue_value_per_share": 11,
    "total_issue_value": 34760,
    "face_value_per_share": 10,
    "face_value": 31600,
    "type_of_capital": "Equity",
    "class_of_capital": "Class 2"
  },
  {
    "sl_no": 9,
    "shareholder_name": "James Harris",
    "no_of_shares": 405,
    "date_of_issue": "2024-10-25",
    "instrument_no_from": 3423,
    "instrument_no_to": 8239,
    "mode_of_issue": "Bonus",
    "is_promoter": "Yes",
    "consideration": "Cash",
    "issue_value_per_share": 101,
    "total_issue_value": 40905,
    "face_value_per_share": 100,
    "face_value": 40500,
    "type_of_capital": "Equity",
    "class_of_capital": "Class 2"
  },
  {
    "sl_no": 10,
    "shareholder_name": "Linda Martin",
    "no_of_shares": 3821,
    "date_of_issue": "2024-05-29",
    "instrument_no_from": 1402,
    "instrument_no_to": 6631,
    "mode_of_issue": "Bonus",
    "is_promoter": "Yes",
    "consideration": "Contract",
    "issue_value_per_share": 113,
    "total_issue_value": 431773,
    "face_value_per_share": 100,
    "face_value": 382100,
    "type_of_capital": "Preference",
    "class_of_capital": "Class 2"
  },
  {
    "sl_no": 11,
    "shareholder_name": "Thomas Anderson",
    "no_of_shares": 922,
    "date_of_issue": "2024-09-13",
    "instrument_no_from": 4256,
    "instrument_no_to": 5758,
    "mode_of_issue": "Allotment",
    "is_promoter": "Yes",
    "consideration": "ESOP",
    "issue_value_per_share": 13,
    "total_issue_value": 11986,
    "face_value_per_share": 10,
    "face_value": 9220,
    "type_of_capital": "Equity",
    "class_of_capital": "Class 2"
  },
  {
    "sl_no": 12,
    "shareholder_name": "Karen Thomas",
    "no_of_shares": 4480,
    "date_of_issue": "2023-03-21",
    "instrument_no_from": 3527,
    "instrument_no_to": 5812,
    "mode_of_issue": "Split",
    "is_promoter": "Yes",
    "consideration": "ESOP",
    "issue_value_per_share": 116,
    "total_issue_value": 519680,
    "face_value_per_share": 100,
    "face_value": 448000,
    "type_of_capital": "Equity",
    "class_of_capital": "Class 2"
  },
  {
    "sl_no": 13,
    "shareholder_name": "Charles Jackson",
    "no_of_shares": 3694,
    "date_of_issue": "2024-08-13",
    "instrument_no_from": 1352,
    "instrument_no_to": 5262,
    "mode_of_issue": "Allotment",
    "is_promoter": "No",
    "consideration": "Cash",
    "issue_value_per_share": 56,
    "total_issue_value": 206864,
    "face_value_per_share": 50,
    "face_value": 184700,
    "type_of_capital": "Preference",
    "class_of_capital": "Class 2"
  },
  {
    "sl_no": 14,
    "shareholder_name": "Patricia Lee",
    "no_of_shares": 1423,
    "date_of_issue": "2024-06-02",
    "instrument_no_from": 2594,
    "instrument_no_to": 6678,
    "mode_of_issue": "Bonus",
    "is_promoter": "No",
    "consideration": "Contract",
    "issue_value_per_share": 19,
    "total_issue_value": 27037,
    "face_value_per_share": 10,
    "face_value": 14230,
    "type_of_capital": "Preference",
    "class_of_capital": "Class 2"
  },
  {
    "sl_no": 15,
    "shareholder_name": "Daniel Lewis",
    "no_of_shares": 4289,
    "date_of_issue": "2024-04-10",
    "instrument_no_from": 4111,
    "instrument_no_to": 7307,
    "mode_of_issue": "Split",
    "is_promoter": "No",
    "consideration": "Cash",
    "issue_value_per_share": 62,
    "total_issue_value": 265918,
    "face_value_per_share": 50,
    "face_value": 214450,
    "type_of_capital": "Preference",
    "class_of_capital": "Class 1"
  },
  {
    "sl_no": 16,
    "shareholder_name": "Barbara Walker",
    "no_of_shares": 2559,
    "date_of_issue": "2021-06-01",
    "instrument_no_from": 2275,
    "instrument_no_to": 5012,
    "mode_of_issue": "Split",
    "is_promoter": "Yes",
    "consideration": "Cash",
    "issue_value_per_share": 24,
    "total_issue_value": 61416,
    "face_value_per_share": 10,
    "face_value": 25590,
    "type_of_capital": "Equity",
    "class_of_capital": "Class 2"
  },
  {
    "sl_no": 17,
    "shareholder_name": "Matthew Hall",
    "no_of_shares": 2850,
    "date_of_issue": "2022-03-06",
    "instrument_no_from": 1353,
    "instrument_no_to": 5504,
    "mode_of_issue": "Split",
    "is_promoter": "Yes",
    "consideration": "Conversion",
    "issue_value_per_share": 116,
    "total_issue_value": 330600,
    "face_value_per_share": 100,
    "face_value": 285000,
    "type_of_capital": "Preference",
    "class_of_capital": "Class 2"
  },
  {
    "sl_no": 18,
    "shareholder_name": "Susan Allen",
    "no_of_shares": 1873,
    "date_of_issue": "2021-12-05",
    "instrument_no_from": 1498,
    "instrument_no_to": 6248,
    "mode_of_issue": "Split",
    "is_promoter": "No",
    "consideration": "Cash",
    "issue_value_per_share": 15,
    "total_issue_value": 28095,
    "face_value_per_share": 10,
    "face_value": 18730,
    "type_of_capital": "Equity",
    "class_of_capital": "Class 2"
  },
  {
    "sl_no": 19,
    "shareholder_name": "Christopher Young",
    "no_of_shares": 1005,
    "date_of_issue": "2022-10-15",
    "instrument_no_from": 3473,
    "instrument_no_to": 5704,
    "mode_of_issue": "Allotment",
    "is_promoter": "Yes",
    "consideration": "Cash",
    "issue_value_per_share": 115,
    "total_issue_value": 115575,
    "face_value_per_share": 100,
    "face_value": 100500,
    "type_of_capital": "Equity",
    "class_of_capital": "Class 2"
  },
  {
    "sl_no": 20,
    "shareholder_name": "Jessica King",
    "no_of_shares": 4476,
    "date_of_issue": "2020-08-14",
    "instrument_no_from": 2924,
    "instrument_no_to": 8997,
    "mode_of_issue": "Split",
    "is_promoter": "No",
    "consideration": "Contract",
    "issue_value_per_share": 120,
    "total_issue_value": 537120,
    "face_value_per_share": 100,
    "face_value": 447600,
    "type_of_capital": "Equity",
    "class_of_capital": "Class 1"
  }
];

module.exports = sharecaptial;
